# TODO: The discrete actions have not been changed (from ridgeback here)
robot:
  holonomic: True
  discrete_actions:
    - name: move_forward
      linear: 2.78
      angular: 0.0
    - name: move_backward
      linear: -0.15
      angular: 0.0
    - name: turn_left
      linear: 0.15
      angular: 0.35
    - name: turn_right
      linear: 0.15
      angular: -0.35
    - name: turn_strong_left
      linear: 0.0
      angular: 0.75
    - name: turn_strong_right
      linear: 0.0
      angular: -0.75
    - name: stop
      linear: 0.0
      angular: 0.0
  dynamic_limits:
    v: [-2.5, 2.5]
    a: [-4,4]
    j: [-8,8]
