# Training Curriculum
# this yaml serves as container of the learning curriculum for the agent
# by determining the number of static/dynamic obstacles per stage
# (will carry on training on last stage when threshhold reached)
1:
  static: 0
  dynamic: 0
2:
  static: 5
  dynamic: 0
3:
  static: 10
  dynamic: 0
4:
  static: 5
  dynamic: 5
5:
  static: 10
  dynamic: 5
6:
  static: 10
  dynamic: 5
7:
  static: 5
  dynamic: 40
8:
  static: 40
  dynamic: 25
9:
  static: 40
  dynamic: 25

# 1:
#   static: 0
#   dynamic: 0
# 2:
#   static: 0
#   dynamic: 4
# 3:
#   static: 0
#   dynamic: 8
# 4:
#   static: 0
#   dynamic: 12
# 5:
#   static: 0
#   dynamic: 16
# 6:
#   static: 0
#   dynamic: 20
# 7:
#   static: 0
#   dynamic: 24
# 8:
#   static: 2
#   dynamic: 28
# 9:
#   static: 2
#   dynamic: 32
# 10:
#   static: 2
#   dynamic: 40

